version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
jobs:
  test-3.7: &test-template
    docker:
    - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          sudo pip install --upgrade pip
          sudo pip install -e .
    - run:
        name: run tests
        command: |
          sudo python setup.py test
  test-3.6:
      <<: *test-template
      docker:
      - image: circleci/python:3.6
  test-3.5:
    <<: *test-template
    docker:
    - image: circleci/python:3.5
